# Upper()
# Lower()
# swapcase()
# Count()
# Startswith()
# Endswith()
# Find()
# Strip()
# split()
# Index()

text = "Messi is the GOAT"
print(text.upper())
print(text.lower())
print(text.swapcase())
print(text.count("i"))
print(text.startswith("s"))
print(text.endswith("s"))
print(text.find("O"))
print(text.strip("i")) 
print(text.split())
print(text.index("G"))